server:
  port: 8082
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allowed-Origin
      routes:
        - id: authenticated_routes
          uri: http://localhost:4000
          predicates:
            - Path=/api/public/**
          filters:
            - name: CustomFilter
              args:
                requestHeaderName: X-Request-Example
                responseHeaderName: X-Response-Example
                responseHeaderValue: Gateway-Response
                requestHeaderValue: Gateway-request-value